#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: $0 [i|d|m|g]"
	exit 65
fi

case $1 in
	i) wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+;;
	d) wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-;;
	m) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle;;
	g) wpctl get-volume @DEFAULT_AUDIO_SINK@;;
esac

dwmstatus
